--
namespace: community
name: wordpress-role
version: 1.0.1
readme: README.md
authors:
  - Aurelien
description: Install wordpress
license_file: COPYING
tags:
  - v1
repository: https://github.com/GacruxM4/wordpress_role.git
documentation: https://github.com/GacruxM4/wordpress_role.git
homepage: https://github.com/GacruxM4/wordpress_role.git
issues: https://github.com/GacruxM4/wordpress_role.git
build_ignore:
  - .gitignore