---
# tasks file for wordpress_role
- name: Create a network
  docker_network:
    name: "{{ network }}"

- name: "create mysql container"
  docker_container:
    name: "{{ mysql_container_name }}"
    image: mysql:5.7
    env:
          MYSQL_ROOT_PASSWORD: "{{ wp_db_password }}"
          MYSQL_DATABASE: "{{ wp_db_name }}"
          MYSQL_USER: "{{ wp_mysql_user }}"
          MYSQL_PASSWORD: "{{ wp_db_password }}"
    volumes:
      - '{{ mysql_volume_name }}:/var/lib/mysql'

- name: "create wordpress container"
  docker_container:
    name: "{{ wp_container_name }}"
    image: wordpress
    ports:
      - '{{ wp_port }}:80'
    env:
          WORDPRESS_DB_HOST: mysql_host
          WORDPRESS_DB_USER: "{{ wp_mysql_user }}"
          WORDPRESS_DB_PASSWORD: "{{ wp_db_password }}"
          WORDPRESS_DB_NAME: "{{ wp_db_name }}"
    links:
      - '{{ mysql_container_name }}:mysql_host'
    volumes:
      - '{{ wp_volume_name }}:/var/www/html'

- name: Add container to network
  docker_network:
    name: "{{ network }}"
    connected:
      - "{{ mysql_container_name }}"
      - "{{ wp_container_name }}"
    appends: yes